"use client"; 

import Head from 'next/head';
import styled from 'styled-components';
import Card from '../app/components/Card';

const PageContainer = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  min-height: 100vh;
  background: linear-gradient(135deg, #f6d365 0%, #fda085 100%);
  padding: 20px;
`;

const Title = styled.h1`
  color: #fff;
  font-size: 36px;
  margin-bottom: 40px;
  text-align: center;
`;

const Home = () => {
  const userData = {
    nome: 'Ivan Giuseppe',
    cognome: 'Saltaformaggio',
    dataNascita: '22/01/1996',
    luogoNascita: 'Lentini (SR)',
    professione: 'Frontend Developer',
    hobby: ['larp', 'videogame', 'escursioni', 'storia'],
  };

  return (
    <PageContainer>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Title>Benvenuto nella mia Home Page</Title>
      <Card {...userData} />
    </PageContainer>
  );
};

export default Home;
